# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.126.1" # pick a version Netlify supports
  HUGO_EXTENDED = "true"

[context.production.environment]
  HUGO_VERSION = "0.111.3"  # example of a known working version
  HUGO_ENV = "production"
  NODE_VERSION = "18"
